[package]
name = "protobuf_to_zod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.22"
nom = "7.1.3"
criterion = "0.5"
heck = "0.4"
petgraph = "0.6"

[dev-dependencies]
protobuf_to_zod = { path = "." }

[[bench]]
name = "parser_benchmark"
harness = false
