use protobuf_to_zod::generator::zod_generator::generate_zod_schemas;
use protobuf_to_zod::parser::ast::{
    Enum, EnumValue, Field, FieldLabel, FieldType, Message, NumberValue, ProtoFile,
};

fn create_test_proto_file() -> ProtoFile {
    ProtoFile {
        enums: vec![Enum {
            name: "Gender".to_string(),
            values: vec![
                EnumValue {
                    name: "GENDER_UNSPECIFIED".to_string(),
                    number: NumberValue::DecimalInt(0),
                    options: vec![],
                },
                EnumValue {
                    name: "GENDER_MALE".to_string(),
                    number: NumberValue::DecimalInt(1),
                    options: vec![],
                },
                EnumValue {
                    name: "GENDER_FEMALE".to_string(),
                    number: NumberValue::DecimalInt(2),
                    options: vec![],
                },
                EnumValue {
                    name: "GENDER_OTHER".to_string(),
                    number: NumberValue::DecimalInt(3),
                    options: vec![],
                },
            ],
            options: vec![],
        }],
        messages: vec![Message {
            name: "Person".to_string(),
            fields: vec![
                Field {
                    name: "name".to_string(),
                    label: FieldLabel::Optional,
                    typ: FieldType::String,
                    number: NumberValue::DecimalInt(1),
                    options: vec![],
                },
                Field {
                    name: "age".to_string(),
                    label: FieldLabel::Optional,
                    typ: FieldType::Int32,
                    number: NumberValue::DecimalInt(2),
                    options: vec![],
                },
                Field {
                    name: "gender".to_string(),
                    label: FieldLabel::Optional,
                    typ: FieldType::MessageOrEnum("Gender".to_string()),
                    number: NumberValue::DecimalInt(3),
                    options: vec![],
                },
                Field {
                    name: "birthdate".to_string(),
                    label: FieldLabel::Optional,
                    typ: FieldType::MessageOrEnum("google.protobuf.Timestamp".to_string()),
                    number: NumberValue::DecimalInt(4),
                    options: vec![],
                },
                Field {
                    name: "events".to_string(),
                    label: FieldLabel::Optional,
                    typ: FieldType::Map(
                        Box::new(FieldType::String),
                        Box::new(FieldType::MessageOrEnum(
                            "google.protobuf.Timestamp".to_string(),
                        )),
                    ),
                    number: NumberValue::DecimalInt(5),
                    options: vec![],
                },
            ],
            oneofs: vec![],
            nested_messages: vec![],
            nested_enums: vec![],
            options: vec![],
            reserved: vec![],
        }],
        syntax: protobuf_to_zod::parser::ast::Syntax::Proto3,
        package: Option::Some("com.foo.bar".to_string()),
        imports: vec![],
        options: vec![],
        services: vec![],
    }
}

#[test]
fn test_generate_zod_schemas() {
    let proto_file = create_test_proto_file();
    let zod_schemas = generate_zod_schemas(&proto_file);

    let expected_output = r#"/* eslint-disable */
// This file was generated by protobuf2zod
// Do not modify this file manually

import { z } from 'zod';

export enum Gender {
  Unspecified = 0,
  Male = 1,
  Female = 2,
  Other = 3,
}
export const GenderSchema = z.nativeEnum(Gender);

export const PersonSchema = z.object({
  name: z.string(),
  age: z.number().int(),
  gender: GenderSchema,
  birthdate: z.instanceof(Date),
  events: z.record(z.string(), z.instanceof(Date)),
});
export type Person = z.infer<typeof PersonSchema>;"#;

    assert_eq!(zod_schemas, expected_output);
}
