use crate::parser::ast::{
    Enum, EnumValue, Field, FieldLabel, FieldType, Message, OneOf, ProtoFile,
};
use heck::ToLowerCamelCase;
use petgraph::algo::toposort;
use petgraph::graphmap::DiGraphMap;
use std::collections::HashSet;
use std::fmt::Write;

/// Generates Zod schemas from a `ProtoFile`.
///
/// # Arguments
///
/// * `proto_file` - A reference to the `ProtoFile` containing the parsed Protobuf definitions.
///
/// # Returns
///
/// A `String` containing the generated Zod schemas.
pub fn generate_zod_schemas(proto_file: &ProtoFile) -> String {
    let mut output = String::new();

    writeln!(output, "/* eslint-disable */").unwrap();
    writeln!(output, "// This file was generated by protobuf2zod").unwrap();
    writeln!(output, "// Do not modify this file manually\n").unwrap();
    writeln!(output, "import {{ z }} from 'zod';\n").unwrap();

    // Generate enums before messages to prevent variable used before declaration errors
    for enum_def in &proto_file.enums {
        generate_enum_schema(&mut output, enum_def);
    }

    // Build dependency graph for message schemas
    let mut graph = DiGraphMap::new();
    let mut message_names = HashSet::new();
    for message in &proto_file.messages {
        message_names.insert(&message.name);
        graph.add_node(&message.name);
    }
    for message in &proto_file.messages {
        for field in &message.fields {
            if let FieldType::MessageOrEnum(ref name) = field.typ {
                if message_names.contains(name) {
                    graph.add_edge(&message.name, name, ());
                }
            }
        }
    }

    // Perform topological sort to determine the correct order
    let sorted_messages = toposort(&graph, None).expect("Cyclic dependency detected");

    // Generate message schemas in the sorted order
    for message_name in sorted_messages {
        let message = proto_file
            .messages
            .iter()
            .find(|m| &m.name == message_name)
            .unwrap();
        generate_message_schema(&mut output, message);
    }

    output.trim_end().to_string()
}

/// Generates a Zod schema for a message.
///
/// # Arguments
///
/// * `output` - A mutable reference to a `String` to write the generated schema to.
/// * `message` - A reference to the `Message` for which to generate the schema.
fn generate_message_schema(output: &mut String, message: &Message) {
    writeln!(output, "export const {}Schema = z.object({{", message.name).unwrap();
    for field in &message.fields {
        generate_field(output, field, false);
    }
    for oneof in &message.oneofs {
        generate_oneof_schema(output, oneof);
    }
    writeln!(output, "}});").unwrap();
    writeln!(
        output,
        "export type {0} = z.infer<typeof {0}Schema>;\n",
        message.name
    )
    .unwrap();
}

/// Generates a Zod schema for a field.
///
/// # Arguments
///
/// * `output` - A mutable reference to a `String` to write the generated schema to.
/// * `field` - A reference to the `Field` for which to generate the schema.
/// * `is_oneof` - A boolean indicating whether the field is part of a `oneof` block.
fn generate_field(output: &mut String, field: &Field, is_oneof: bool) {
    let field_type = generate_zod_type(&field.typ);

    let field_type = if let FieldLabel::Repeated = field.label {
        format!("{}.array()", field_type)
    } else {
        field_type
    };

    let field_name = to_camel_case(&field.name);
    if is_oneof {
        writeln!(
            output,
            "    z.object({{ {}: {} }}),",
            field_name, field_type
        )
        .unwrap();
    } else {
        writeln!(output, "  {}: {},", field_name, field_type).unwrap();
    }
}

/// Generates a Zod type for a given `FieldType`.
///
/// # Arguments
///
/// * `field_type` - A reference to the `FieldType` for which to generate the Zod type.
///
/// # Returns
///
/// A `String` containing the generated Zod type.
fn generate_zod_type(field_type: &FieldType) -> String {
    match field_type {
        FieldType::Double | FieldType::Float => "z.number()".to_string(),
        FieldType::Int32
        | FieldType::Int64
        | FieldType::UInt32
        | FieldType::UInt64
        | FieldType::SInt32
        | FieldType::SInt64
        | FieldType::Fixed32
        | FieldType::Fixed64
        | FieldType::SFixed32
        | FieldType::SFixed64 => "z.number().int()".to_string(),
        FieldType::Bool => "z.boolean()".to_string(),
        FieldType::String => "z.string()".to_string(),
        FieldType::Bytes => "z.instanceof(Uint8Array)".to_string(),
        FieldType::MessageOrEnum(ref name) => {
            if name == "google.protobuf.Timestamp" {
                "z.instanceof(Date)".to_string()
            } else if name.contains('.') {
                "z.unknown()".to_string()
            } else {
                format!("{}Schema", name.clone())
            }
        }
        FieldType::Map(ref key_type, ref value_type) => {
            let key_type_str = generate_zod_type(key_type);
            let value_type_str = generate_zod_type(value_type);
            format!("z.record({}, {})", key_type_str, value_type_str)
        }
    }
}

/// Generates a Zod schema for a `oneof` block.
///
/// # Arguments
///
/// * `output` - A mutable reference to a `String` to write the generated schema to.
/// * `oneof` - A reference to the `OneOf` block for which to generate the schema.
fn generate_oneof_schema(output: &mut String, oneof: &OneOf) {
    writeln!(output, "  {}: z.union([", to_camel_case(&oneof.name)).unwrap();
    for field in &oneof.fields {
        generate_field(output, field, true);
    }
    writeln!(output, "  ]),").unwrap();
}

/// Generates a Zod schema for an `enum`.
///
/// # Arguments
///
/// * `output` - A mutable reference to a `String` to write the generated schema to.
/// * `enum_def` - A reference to the `Enum` for which to generate the schema.
fn generate_enum_schema(output: &mut String, enum_def: &Enum) {
    writeln!(output, "export const {}Schema = z.enum([", enum_def.name).unwrap();
    let prefix = find_common_prefix(&enum_def.values);
    for value in &enum_def.values {
        let stripped_value = value.name.strip_prefix(&prefix).unwrap_or(&value.name);
        writeln!(output, "  '{}',", stripped_value).unwrap();
    }
    writeln!(output, "]);").unwrap();
    writeln!(
        output,
        "export type {0} = z.infer<typeof {0}Schema>;\n",
        enum_def.name
    )
    .unwrap();
}

/// Converts a string to camel case.
///
/// # Arguments
///
/// * `s` - A reference to the string to convert.
///
/// # Returns
///
/// A `String` containing the camel case version of the input string.
fn to_camel_case(s: &str) -> String {
    s.to_lower_camel_case()
}

/// Finds the common prefix in a list of enum values.
///
/// # Arguments
///
/// * `values` - A reference to a slice of `EnumValue`.
///
/// # Returns
///
/// A `String` containing the common prefix of the enum values.
fn find_common_prefix(values: &[EnumValue]) -> String {
    if values.is_empty() {
        return String::new();
    }

    let first = &values[0].name;
    let mut prefix_len = first.len();

    for value in values.iter().skip(1) {
        prefix_len = prefix_len.min(value.name.len());
        for (i, (c1, c2)) in first.chars().zip(value.name.chars()).enumerate() {
            if c1 != c2 {
                prefix_len = i;
                break;
            }
        }
    }

    first[..prefix_len].to_string()
}
