/* eslint-disable */
// This file was generated by protobuf2zod
// Do not modify this file manually

import { z } from 'zod';

export const LogTypeSchema = z.enum([
  'UNSPECIFIED',
  'BUCK_LOG',
  'BUCK_MACHINE_LOG',
  'CHROME_TRACE_LOG',
  'SIMPLE_CONSOLE_LOG',
  'CRITICAL_PATH_LOG',
  'RULE_KEY_LOG',
]);
export type LogType = z.infer<typeof LogTypeSchema>;

export const LogMessageSchema = z.object({
  logId: z.number().int(),
  logMessage: z.string(),
});
export type LogMessage = z.infer<typeof LogMessageSchema>;

export const CreateLogResponseSchema = z.object({
  logId: z.number().int(),
});
export type CreateLogResponse = z.infer<typeof CreateLogResponseSchema>;

export const CreateLogRequestSchema = z.object({
  logFilePath: z.string(),
  logType: LogTypeSchema,
});
export type CreateLogRequest = z.infer<typeof CreateLogRequestSchema>;
