/* eslint-disable */
// This file was generated by protobuf2zod
// Do not modify this file manually

import { z } from 'zod';

export enum LogType {
  Unspecified = 0,
  BuckLog = 1,
  BuckMachineLog = 2,
  ChromeTraceLog = 3,
  SimpleConsoleLog = 4,
  CriticalPathLog = 5,
  RuleKeyLog = 6,
}
export const LogTypeSchema = z.nativeEnum(LogType);

export const LogMessageSchema = z.object({
  logId: z.number().int(),
  logMessage: z.string(),
});
export type LogMessage = z.infer<typeof LogMessageSchema>;

export const CreateLogResponseSchema = z.object({
  logId: z.number().int(),
});
export type CreateLogResponse = z.infer<typeof CreateLogResponseSchema>;

export const CreateLogRequestSchema = z.object({
  logFilePath: z.string(),
  logType: LogTypeSchema,
});
export type CreateLogRequest = z.infer<typeof CreateLogRequestSchema>;
