/* eslint-disable */
// This file was generated by protobuf2zod
// Do not modify this file manually

import { z } from 'zod';

const Gender = z.enum([
  'UNSPECIFIED',
  'MALE',
  'FEMALE',
]);
const Person = z.object({
  name: z.string(),
  age: z.number().int(),
  hobbies: z.string().array(),
  gender: Gender,
  attributes: z.record(z.string(), z.string()),
  scores: z.record(z.string(), z.number().int()),
  addresses: z.record(z.number().int(), Address),
  identity: z.union([
    z.object({ nickname: z.string() }),
    z.object({ alias: z.string() }),
  ]),
});
const Address = z.object({
  street: z.string(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
});
