/* eslint-disable */
// This file was generated by protobuf2zod
// Do not modify this file manually

import { z } from 'zod';

export enum Gender {
  Unspecified = 0,
  Male = 1,
  Female = 2,
  Other = 3,
}
export const GenderSchema = z.nativeEnum(Gender);

export const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
});
export type Address = z.infer<typeof AddressSchema>;

export const PersonSchema = z.object({
  name: z.string(),
  age: z.number().int(),
  hobbies: z.string().array(),
  gender: GenderSchema,
  attributes: z.record(z.string(), z.string()),
  scores: z.record(z.string(), z.number().int()),
  addresses: z.record(z.number().int(), AddressSchema),
  birthdate: z.instanceof(Date),
  events: z.record(z.string(), z.instanceof(Date)),
  identity: z.union([
    z.object({ nickname: z.string() }),
    z.object({ alias: z.string() }),
  ]),
});
export type Person = z.infer<typeof PersonSchema>;
