/* eslint-disable */
// This file was generated by protobuf2zod
// Do not modify this file manually

import { z } from 'zod';

const Gender = z.enum([
  'UNSPECIFIED',
  'MALE',
  'FEMALE',
]);
const Person = z.object({
  name: z.string(),
  age: z.number().int(),
  hobbies: z.string().array(),
  gender: Gender,
  identity: z.union([
    z.object({ nickname: z.string() }),
    z.object({ alias: z.string() }),
  ]),
});
